### ISSUE TITLE
强制传参对象匹配后不能为null

### ISSUE THREAD

**Issue by xuanhuangkeji** [Smart-Kit/SmartSql#50]
比如在批量删除场景下，我们需要多条件删除，如果传参对象在QueryParams均未匹配到，那么将会直接把整个表给清空

<Statement Id="Delete">
  Delete From test
  <Include RefId="QueryParams" />
</Statement>
_testService.Delete(new{xxid=1});

如果xxid没有在QueryParams中匹配到，test表里面的数据将全部被删除

**Comment by Ahoo-Wang** [comment]
https://github.com/Smart-Kit/SmartSql/commit/15121ee32e988726a6810386da1c045bfc1b95a4
