### ISSUE TITLE
AOP事务判断事务状态

### ISSUE THREAD

**Issue by ywj6792341** [Smart-Kit/SmartSql#59]
在主方法和子方法都存在TransactionAttribute 的情况下。会出异常。AspectCore.DynamicProxy.AspectInvocationException: Exception has been thrown by the aspect of an invocation. ---> Before RollbackTransaction,Please BeginTransaction first!. ---> SmartSql.Exceptions.SmartSqlException: Before RollbackTransaction,Please BeginTransaction first!

如果能在 Invoke 里面判断一下当前事务状态话，在事务已经Begin之后就不要再操作事务了。这样应该可以解决这个问题。

**Comment by Ahoo-Wang** [comment]
你可以选择提交一下PR

**Comment by Ahoo-Wang** [comment]
https://github.com/Smart-Kit/SmartSql/commit/4255778974d6c7a761a3121b4fe6e12c9a47b933
